FROM matttrent/deeplearn

RUN apt-get update \
    && \
    apt-get -y install zsh \
    && \
    chsh -s $(which zsh) $(whoami)

RUN cd $HOME \
    && \
    git clone https://github.com/matttrent/dotfiles.git \
    && \
    cd dotfiles \
    && \
    bash install.sh
